"""
created this manually by reviewing the topic information from the emailClassifer-50 model
created top level labels, then went through and grouped topics by their label.
"""

topic_labels = {
    0: "Orders, Delivery",
    1: "Career, Technology",
    2: "Transactions/Bills",
    7: "Transactions/Bills",
    27: "Transactions/Bills",
    34: "Transactions/Bills",
    35: "Transactions/Bills",
    36: "Transactions/Bills",
    45: "Transactions/Bills",
    47: "Transactions/Bills",
    3: "Promotional",
    4: "Promotional",
    5: "Promotional",
    8: "Promotional",
    12: "Promotional",
    22: "Promotional",
    24: "Promotional",
    37: "Promotional",
    38: "Promotional",
    39: "Promotional",
    44: "Promotional",
    6: "Entertainment",
    15: "Entertainment",
    31: "Entertainment",
    46: "Entertainment",
    9: "Video Games/PC Gaming",
    20: "Video Games/PC Gaming",
    10: "Social Media",
    11: "Finances",
    14: "Finances",
    18: "Finances",
    26: "Finances",
    13: "Account Access",
    23: "Account Access",
    48: "Account Access",
    16: "Calendar/Agenda",
    17: "Real Estate",
    19: "Coffee",
    21: "ISP",
    25: "Politics",
    33: "Politics",
    40: "Politics",
    28: "SPAM",
    41: "SPAM",
    29: "Personal Server Alerting",
    30: "Shipping",
    32: "Code",
    42: "Healthcare",
    43: "Reports",
}
